#
# Exposes a volume with application code to 
# the server containers (PHP, Nginx).
#
# This container is for development environments 
# to which application code is mounted into at 
# runtime.
#
# See "app-code-static" for the production equivalent.
#

FROM ubuntu:14.04

MAINTAINER Markus Weiland <mw@graph-ix.net>

VOLUME /var/www/symfony

